
name: Explain KEYS_TO_IGNORE

on: [workflow_dispatch]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get OpenRCT2 develop (for en-GB.txt)
        uses: actions/checkout@v4
        with:
          repository: OpenRCT2/OpenRCT2
          ref: develop
          path: OpenRCT2

    
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Checkout upstream master (in order to use the newest version of the script)
        uses: actions/checkout@v4
        with:
          repository: tygrysek90/l10n-action-ideas-testing
          ref: main
          path: upstream_master

      - name: _EXPLAIN KEYS_
        run: python upstream_master/.github/workflows/explain.py
